[[redirects]]
  from = "/register"
  to = "https://odia-preneur.onrender.com/register"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/"
  to = "https://odia-preneur.onrender.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
